"use strict";

exports.REQUEST_DOMAINS_UPDATE = "API:REQUEST_DOMAINS_UPDATE";
exports.REQUEST_DOMAINS_UPDATE_FAILURE = "API:REQUEST_DOMAINS_UPDATE_FAILURE";
exports.REQUEST_DOMAINS_UPDATE_SUCCESS = "API:REQUEST_DOMAINS_UPDATE_SUCCESS";
