"use strict";

exports.SAVE_FLATTRS = "DB:SAVE_FLATTRS";
exports.SAVE_FLATTRS_MERGE_PENDING = "DB:SAVE_FLATTRS_MERGE_PENDING";
exports.SAVE_FLATTRS_SUCCESS = "DB:SAVE_FLATTRS_SUCCESS";
exports.SUBMIT_FLATTRS = "API:SUBMIT_FLATTRS";
exports.SUBMIT_FLATTRS_MERGE_PENDING = "API:SUBMIT_FLATTRS_MERGE_PENDING";
exports.SUBMIT_FLATTRS_SUCCESS = "API:SUBMIT_FLATTRS_SUCCESS";
exports.SUBMIT_FLATTRS_FAILURE = "API:SUBMIT_FLATTRS_FAILURE";
