"use strict";

exports.SAVE_TIMESTAMP = "DB:SAVE_TIMESTAMP";
exports.SAVE_TIMESTAMP_MERGE_PENDING = "DB:SAVE_TIMESTAMP_MERGE_PENDING";
exports.SAVE_TIMESTAMP_SUCCESS = "DB:SAVE_TIMESTAMP_SUCCESS";
exports.SAVE_TIMESTAMP_FAILURE = "DB:SAVE_TIMESTAMP_FAILURE";
